backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "home"
    label: "Página Inicial"
    files:
      - label: "Conteúdo Principal"
        name: "conteudo"
        file: "dados.json"
        fields:
          - { label: "Título Principal (Hero)", name: "titulo_site", widget: "string" }
          - { label: "Subtítulo/Descrição", name: "descricao_site", widget: "text" }
          - { label: "Cor de Destaque", name: "cor_fundo", widget: "color", default: "#e67e22" }
          
      - label: "Sobre Nós"
        name: "sobre"
        file: "dados.json"
        fields:
          - { label: "Título Sobre", name: "sobre_titulo", widget: "string" }
          - { label: "Texto Sobre Nós", name: "sobre_texto", widget: "markdown" }

      - label: "Áreas de Atuação"
        name: "areas"
        file: "dados.json"
        fields:
          - { label: "Título Seção Áreas", name: "areas_titulo", widget: "string" }
          - { label: "Descrição Áreas", name: "areas_descricao", widget: "text" }

      - label: "Onde Estamos"
        name: "localizacao"
        file: "dados.json"
        fields:
          - { label: "Título Onde Estamos", name: "onde_titulo", widget: "string" }
          - { label: "Unidades (Texto)", name: "unidades_texto", widget: "text" }
