backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - label: "Página Inicial"
        name: "home"
        file: "dados.json"
        fields:
          - { label: "Título Principal (Hero)", name: "titulo_site", widget: "string" }
          - { label: "Subtítulo (Hero)", name: "descricao_site", widget: "text" }
          - { label: "Título Sobre Nós", name: "sobre_titulo", widget: "string" }
          - { label: "Texto Sobre Nós", name: "sobre_texto", widget: "markdown" }
          - { label: "Título Áreas de Atuação", name: "areas_titulo", widget: "string" }
          - { label: "Descrição das Áreas", name: "areas_desc", widget: "text" }
          - { label: "Título Onde Estamos", name: "onde_titulo", widget: "string" }
          - { label: "WhatsApp (Apenas números)", name: "whatsapp", widget: "string" }
